import { DarkTheme, DefaultTheme } from '@react-navigation/native';
import { COLORS } from './colors';

const AppThemeDefinition = {
  Light: {
    ...DefaultTheme,
    dark: false,
    colors: {
      ...DefaultTheme.colors,
      primary: COLORS.deepIndigo,
      background: COLORS.paleGrey,
      card: COLORS.white,
      text: COLORS.textDark,
      border: COLORS.shadowGrey,
      notification: COLORS.googleRed,

      white: COLORS.white,
      black: COLORS.black,
      mainBackground: COLORS.paleGrey,
      cartContainer: COLORS.white,
      headerBackground: COLORS.deepIndigo,
      headerText: COLORS.white,
      drawerColor: COLORS.deepIndigo,
      drawerSelected: COLORS.blackAlpha20,
      drawerTitleColor: COLORS.skyBlue,
      drawerHeader: COLORS.whiteAlpha90,
      sidebarDivider: COLORS.whiteAlpha20,
      brandAccent: COLORS.deepIndigo,
      lotteryBox: COLORS.deepIndigo,
      switchBackground: COLORS.switchBgLight,
      boxShadow: COLORS.shadowGrey,
      spinnerColor: COLORS.deepIndigo,
      fontWhite: COLORS.white,
      fontMainColor: COLORS.textDark,
      fontSecondColor: COLORS.textMutedLight,
      yellow: COLORS.yellow,
      green: COLORS.green,
      google: COLORS.googleRed,
      facebook: COLORS.facebookBlue,
      activeColor: COLORS.mintGreen,
      checkBoxColor: COLORS.skyBlue,
    },
  },
  Dark: {
    ...DarkTheme,
    dark: true,
    colors: {
      ...DarkTheme.colors,
      primary: COLORS.softViolet,
      background: COLORS.nearBlack,
      card: COLORS.darkSurface,
      text: COLORS.white,
      border: COLORS.darkBorder,
      notification: COLORS.googleRed,

      white: COLORS.white,
      black: COLORS.black,
      mainBackground: COLORS.nearBlack,
      cartContainer: COLORS.darkSurface,
      headerBackground: COLORS.darkElevated,
      headerText: COLORS.white,
      drawerColor: COLORS.darkElevated,
      drawerSelected: COLORS.whiteAlpha15,
      drawerTitleColor: COLORS.softViolet,
      drawerHeader: COLORS.blackAlpha60,
      sidebarDivider: COLORS.whiteAlpha15,
      brandAccent: COLORS.softViolet,
      lotteryBox: COLORS.softViolet,
      switchBackground: COLORS.switchBgDark,
      boxShadow: COLORS.shadowBlack,
      spinnerColor: COLORS.softViolet,
      fontWhite: COLORS.white,
      fontMainColor: COLORS.white,
      fontSecondColor: COLORS.textMutedDark,
      yellow: COLORS.yellow,
      green: COLORS.green,
      google: COLORS.googleRed,
      facebook: COLORS.facebookBlue,
      activeColor: COLORS.mintGreen,
      checkBoxColor: COLORS.softViolet,
    },
  },
} as const satisfies { Light: NavigationTheme; Dark: NavigationTheme };

export const THEME = AppThemeDefinition;
